name: Publish Package on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup sbt
        uses: olafurpg/setup-scala@v11
        with:
          sbt-version: 1.9.9
          scala-version: 2.13.16

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Setup sbt credentials
        run: |
          mkdir -p ~/.sbt/1.0
          echo "credentials += Credentials(\"GitHub Package Registry\", \"maven.pkg.github.com\", \"${{ github.actor }}\", \"${{ secrets.GITHUB_TOKEN }}\")" >> ~/.sbt/1.0/global.sbt

      - name: Build and publish for Scala 2.13
        run: |
          sbt ++2.13.16 clean compile publishM2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish for Scala 2.13
        run: |
          sbt ++2.13.16 publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish for Scala 3
        run: |
          sbt ++3.3.4 clean compile publishM2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish for Scala 3
        run: |
          sbt ++3.3.4 publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
