name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'


      - name: Setup sbt
        uses: olafurpg/setup-scala@v11
        with:
          sbt-version: 1.9.9
          scala-version: 2.13.16


      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Run tests for Scala 2.13
        run: sbt ++2.13.16 clean compile test

      - name: Run tests for Scala 3
        run: sbt ++3.3.4 clean compile test

#      - name: Sbt Dependency Submission for Scala 2.13
#        uses: scalacenter/sbt-dependency-submission@v3.0.1
#
#      - name: Sbt Dependency Submission for Scala 3
#        uses: scalacenter/sbt-dependency-submission@v3.0.1
